name: 🔁 Update README with Commit Count

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install axios

      - name: Run commit count updater
        run: node ./scripts/updateCommits.js
        env:
          GH_USERNAME: siyabuilds
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update commit badge"
            git push
          else
            echo "No changes to commit."
          fi
